# .bash_aliases - login shell configuration:
#  useful aliases for a variety of cases:

# make rm safe(r):
alias rm='rm -iv'	# rm will require a y/n confirmation and will also be verbose:
					# can be overridden by -rf:

# detect which `ls` flavor is in use:
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi

# Always use color output for `ls`:
# - this color setup is similar to my linux 'ls colors', listings show up more
#   clearly and readable on a transparent terminal
#   refer to 'man ls > LSCOLORS' for details
export LSCOLORS=ExGxcxdxBxegedabagacad

# various ls formats:
alias ls='ls ${colorflag}'
alias lf='ls -F ${colorflag}'
alias la='lf -A ${colorflag}'
alias ld='lf -ld ${colorflag}'
alias ll='lf -lA ${colorflag}'
alias lx='lf -l ${colorflag}'

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# Always enable colored `grep` output:
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage:
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Show/hide hidden files in Finder:
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Hide/show all desktop icons (useful when presenting):
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Lock the screen (when going AFK):
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Reload the shell (i.e. invoke as a login shell):
alias reload="exec $SHELL -l"

# git commands:
alias glog="git log --oneline --decorate --all --graph"
alias plog="git log --pretty=format:'%h %an %s'"

# tmux shorties:
alias tn='tmux new-session -s'
alias ta='tmux attach -t'
alias tl='tmux ls'
